import React from "react";
import Link from "next/link";
import { CheckCircle2, ArrowLeft, AlertCircle } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#120510] text-[#FDFBF7] py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto space-y-8">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs text-dandiya-gold hover:text-dandiya-gold-light"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Home</span>
        </Link>

        <div className="space-y-2">
          <span className="text-xs uppercase tracking-widest text-dandiya-gold font-bold">
            Guidelines & Rules
          </span>
          <h1 className="text-3xl sm:text-4xl font-serif font-bold text-dandiya-gold-light">
            Terms & Conditions
          </h1>
          <p className="text-xs text-dandiya-ivory/60">
            Dandiya Night 2026 • Student Cultural Council
          </p>
        </div>

        <div className="p-6 sm:p-8 rounded-2xl bg-[#1C0A19]/90 border border-dandiya-border shadow-gold space-y-6 text-sm text-dandiya-ivory/80 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-base font-serif font-bold text-dandiya-gold flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-dandiya-saffron" />
              1. Voluntary Contributions
            </h2>
            <p>
              Contributions made through this web application are voluntary student contributions in support of the annual college Dandiya Night event. There is no automated third-party payment gateway; students transfer funds externally via standard UPI.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-serif font-bold text-dandiya-gold flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-dandiya-saffron" />
              2. UTR Submission & Duplicate Prevention
            </h2>
            <p>
              Each student is responsible for entering the exact 12-digit UPI Reference Number / UTR generated by their payment app. Submitting duplicate, forged, or altered reference numbers is strictly tracked by system audit logs and will result in immediate rejection.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-serif font-bold text-dandiya-gold">
              3. Verification & Approval SLA
            </h2>
            <p>
              Submitting a payment request registers its status as <strong>PENDING</strong>. Funds are officially added to the event pool only once verified against the official bank account statement by the designated student event administrators.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-serif font-bold text-dandiya-gold">
              4. Event Code of Conduct
            </h2>
            <p>
              All students attending Dandiya Night 2026 are expected to uphold collegiate decorum, respect traditional festivities, follow event security protocols, and bring valid college identification cards.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
